[2025-05-22T14:07:36.881+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-22T14:07:36.933+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v02.task1 scheduled__2025-05-21T00:00:00+00:00 [queued]>
[2025-05-22T14:07:36.970+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v02.task1 scheduled__2025-05-21T00:00:00+00:00 [queued]>
[2025-05-22T14:07:36.971+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 6
[2025-05-22T14:07:37.005+0000] {taskinstance.py:2907} INFO - Executing <Task(BashOperator): task1> on 2025-05-21 00:00:00+00:00
[2025-05-22T14:07:37.024+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v02', 'task1', 'scheduled__2025-05-21T00:00:00+00:00', '--job-id', '3941', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmpvkak69yp']
[2025-05-22T14:07:37.027+0000] {standard_task_runner.py:105} INFO - Job 3941: Subtask task1
[2025-05-22T14:07:37.025+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=584) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-22T14:07:37.032+0000] {standard_task_runner.py:72} INFO - Started process 587 to run task
[2025-05-22T14:07:37.120+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_backfill_v02.task1 scheduled__2025-05-21T00:00:00+00:00 [running]> on host 2032228d86df
[2025-05-22T14:07:37.303+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backfill_v02' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T00:00:00+00:00'
[2025-05-22T14:07:37.313+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-05-22T14:07:37.349+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-05-22T14:07:37.353+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2025-05-22T14:07:37.372+0000] {subprocess.py:99} INFO - Output:
[2025-05-22T14:07:37.387+0000] {subprocess.py:106} INFO - This is a simple bash command!
[2025-05-22T14:07:37.389+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-05-22T14:07:37.443+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-05-22T14:07:37.444+0000] {taskinstance.py:361} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backfill_v02, task_id=task1, run_id=scheduled__2025-05-21T00:00:00+00:00, execution_date=20250521T000000, start_date=20250522T140736, end_date=20250522T140737
[2025-05-22T14:07:37.533+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-22T14:07:37.553+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-22T14:07:37.572+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
